-- Create role student
CREATE ROLE student;

GRANT CONNECT ON DATABASE erke TO auditor;
GRANT USAGE ON SCHEMA public TO auditor;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO auditor;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO auditor;

CREATE ROLE organizer;

GRANT CONNECT ON DATABASE erke TO organizer;
GRANT USAGE ON SCHEMA public TO organizer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO organizer;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO organizer;

CREATE ROLE auditor;

GRANT CONNECT ON DATABASE erke TO organizer;
GRANT USAGE ON SCHEMA public TO organizer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO organizer;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO organizer;
